import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

final SizedBox gap0 = SizedBox();
final SizedBox gapW2 = SizedBox(width: 2.w);
final SizedBox gapW4 = SizedBox(width: 4.w);
final SizedBox gapW6 = SizedBox(width: 6.w);
final SizedBox gapW8 = SizedBox(width: 8.w);
final SizedBox gapW12 = SizedBox(width: 12.w);
final SizedBox gapW16 = SizedBox(width: 16.w);
final SizedBox gapW20 = SizedBox(width: 20.w);
final SizedBox gapW24 = SizedBox(width: 24.w);
final SizedBox gapW28 = SizedBox(width: 28.w);
final SizedBox gapW32 = SizedBox(width: 32.w);
final SizedBox gapW36 = SizedBox(width: 36.w);
final SizedBox gapW40 = SizedBox(width: 40.w);
final SizedBox gapW44 = SizedBox(width: 44.w);
final SizedBox gapW48 = SizedBox(width: 48.w);
final SizedBox gapW52 = SizedBox(width: 52.w);
final SizedBox gapW56 = SizedBox(width: 56.w);
final SizedBox gapW60 = SizedBox(width: 60.w);
final SizedBox gapW64 = SizedBox(width: 64.w);

final SizedBox gapH4 = SizedBox(height: 4.h);
final SizedBox gapH8 = SizedBox(height: 8.h);
final SizedBox gapH10 = SizedBox(height: 10.h);
final SizedBox gapH12 = SizedBox(height: 12.h);
final SizedBox gapH16 = SizedBox(height: 16.h);
final SizedBox gapH20 = SizedBox(height: 20.h);
final SizedBox gapH24 = SizedBox(height: 24.h);
final SizedBox gapH28 = SizedBox(height: 28.h);
final SizedBox gapH32 = SizedBox(height: 32.h);
final SizedBox gapH36 = SizedBox(height: 36.h);
final SizedBox gapH40 = SizedBox(height: 40.h);
final SizedBox gapH44 = SizedBox(height: 44.h);
final SizedBox gapH48 = SizedBox(height: 48.h);
final SizedBox gapH52 = SizedBox(height: 52.h);
final SizedBox gapH56 = SizedBox(height: 56.h);
final SizedBox gapH60 = SizedBox(height: 60.h);
final SizedBox gapH64 = SizedBox(height: 64.h);