// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgTTgU9LNzDwiWXmizTNF5eOqjAoBnjzU',
    appId: '1:1067677847291:android:d2ede70d78a0c5b733aa5e',
    messagingSenderId: '1067677847291',
    projectId: 'pointsuite-dev',
    storageBucket: 'pointsuite-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcUyP9uhEETBFe5ETGlDJLIVRgB_J5jCw',
    appId: '1:1067677847291:ios:d8b49acb56439c0d33aa5e',
    messagingSenderId: '1067677847291',
    projectId: 'pointsuite-dev',
    storageBucket: 'pointsuite-dev.appspot.com',
    androidClientId: '1067677847291-4ds8jdbscqqlh6blbmle6pg1ejisduuk.apps.googleusercontent.com',
    iosClientId: '1067677847291-ihbqn11iuhdft8cvgmlkkndi3no3m419.apps.googleusercontent.com',
    iosBundleId: 'xyz.pointsuite.dev',
  );
}
